;; Official Cask Repositories
(source gnu)
(source org)
(source melpa-stable)
(source melpa)
(source marmalade)

;; Elpy source
(source "elpy" "http://jorgenschaefer.github.io/packages/")


;; Packages

(depends-on "cask")
(depends-on "flycheck")
(depends-on "flycheck-cask")


;;;; Org-mode
(depends-on "org-bullets")
(depends-on "org-plus-contrib")
(depends-on "calfw")

;;;; Helm + Projectile + Others
(depends-on "projectile")
(depends-on "helm")
(depends-on "helm-projectile")

;;;; Theme
(depends-on "fill-column-indicator")
(depends-on "highlight-indentation")
(depends-on "rainbow-mode") ;; Show #000 with color
(depends-on "rainbow-delimiters")
(depends-on "color-theme")
(depends-on "powerline")
(depends-on "emojify")

;;;;;; Other themes not used
(depends-on "moe-theme")
(depends-on "atom-one-dark-theme")

;;:: Other must have stuff
(depends-on "smartparens")
(depends-on "yasnippet")
(depends-on "magit")
(depends-on "sr-speedbar")
(depends-on "diff-hl")
(depends-on "clean-aindent-mode")

;;;; Programming

;;;;;; Python
(depends-on "elpy")
(depends-on "virtualenvwrapper")
(depends-on "py-autopep8")

;;;;;; OpenScad
(depends-on "scad-mode")
(depends-on "scad-preview")

;;;;;; Latex
(depends-on "auctex")
(depends-on "latex-preview-pane")

;;;;;; Markdown
(depends-on "markdown-mode")

;;;;;; Company and backends
(depends-on "company")
(depends-on "company-emoji")

;;;;;; Plot
(depends-on "gnuplot")
(depends-on "gnuplot-mode")

;;;; Internet
(depends-on "tumblesocks")
(depends-on "google-translate")
(depends-on "elfeed")

;;;;;; Mail
(depends-on "offlineimap")

;;;; Unnecessary stuff
(depends-on "tea-time")